version: 2.0.{build}
skip_commits:
  message: /NO-BUILD/
  files:
    - docs/*
    - 'LICENSE'
    - 'README.md'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
  - ps: nuget restore
image: Visual Studio 2017
configuration: Release
build:
  parallel: true 
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\bin\**\*.UnitTests.dll'
test_script:
  - cmd: "\"%USERPROFILE%\\.nuget\\packages\\OpenCover\\4.6.519\\tools\\OpenCover.Console.exe\" -register:user -target:\"%xunit20%\\xunit.console.x86.exe\" -targetargs:\"Grumpy.RipplesMQ.Config.UnitTests\\bin\\Release\\Grumpy.RipplesMQ.Config.UnitTests.dll -noshadow\" -output:\"coverage.xml\" -filter:\"+[Grumpy.RipplesMQ.Config*]* -[Grumpy.RipplesMQ.Config.UnitTests*]*\""
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t a2ef8ad2-0959-4e1a-b734-b2fb81ca752d
after_build:
  - ps: nuget pack Grumpy.RipplesMQ.Config\bin\Release\Grumpy.RipplesMQ.Config.nuspec -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
  provider: Environment
  name: NuGet
